spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 30000
      max-lifetime: 3600000             # 60*60*1000
      auto-commit: false
      leak-detection-threshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        userServerPrepStmts: true
        rewriteBatchedInserts: true
  jpa:
    properties:
      hibernate:
        jdbc:
          fetch_size: 400
          batch_size: 100
        order_inserts: true
        order_updates: true